### ISSUE TITLE
Getting error code 404

### ISSUE THREAD

**Issue by mikwehttam** [LukeTowers/oc-gdrivefilesystemdriver-plugin#2]
Hi,

I'm getting this error.

{ "error": { "errors": [ { "domain": "global", "reason": "notFound", "message": "File not found: .", "locationType": "parameter", "location": "fileId" } ], "code": 404, "message": "File not found: ." } }

I followed the instructions, did I miss something? Thanks in advance!

**Comment by LukeTowers** [comment]
Yes, the specified file / folder ID you're trying to access doesn't exist. Double check your configuration

**Comment by mikwehttam** [comment]
Hi Luke, thanks for responding.

This is how I got the folderID, just like the instruction said. I created a new folder.
![image](https://user-images.githubusercontent.com/25194026/51302995-f9babb80-1a6e-11e9-89d5-2fcbf2bc625f.png)

This is my configuration on **cms.php**
    'storage' => [
        'uploads' => [
            'disk'   => 'mygoogledrive',
            'folder' => 'uploads',
            'path'   => '/storage/app/uploads',
        ],
        'media' => [
            'disk'   => 'mygoogledrive',
            'folder' => 'media',
            'path'   => '/storage/app/media',
        ],
    ]

**filesystem.php**
       'mygoogledrive' => [
            'driver' => 'googledrive',
            'clientId' => 'xxxx.apps.googleusercontent.com',
            'clientSecret' => 'xxxx',
            'refreshToken' => 'xxxx',
            'folderId' => '1re62AQHAJ5zmJYTqk8qZ83uyc6f5zaEi'
        ]

I also tried creating a new client id but no luck. Thanks again.

**Comment by mikwehttam** [comment]
Hi, I managed to find the error in my config, **cms.php** should be
'storage' => [
'uploads' => [
'disk' => 'mygoogledrive',
'folder' => '',
'path' => '',
],
'media' => [
'disk' => 'mygoogledrive',
'folder' => '',
'path' => '',
],
]

Thanks!
